version: "2.4"

services:
  backend:
    build:
      context: .
    ports:
      - '3001:3001'
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - LITELOG_MONGO=mongodb://mongo/litelogs
      - LITELOG_PORT=12201
      - LITELOG_IP=0.0.0.0
      - LITELOG_TTL=2
      - LITELOG_API_PORT=3001
      - LITELOG_API_KEY=mysecretkey

  frontend:
    build:
      context: frontend/
      args:
        VUE_APP_API_KEY: "mysecretkey"
        VUE_APP_API_SERVER: "http://localhost:3001"
    ports:
      - "3002:80"
    logging:
      driver: gelf
      options:
        gelf-address: udp://host.docker.internal:12201

  mongo:
    image: mongo:4.0.14
    ports:
        - "27017:27017"
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/litelogs --quiet

  mongoexpress:
    image: mongo-express:0.49
    ports:
        - "8081:8081"
